#!/usr/bin/env python3
"""Build the affinity progress bar out of the lightning bolt.

The bolt is authored upright (lightning-solid, SVG Repo, user-supplied) and the
bar needs it lying down and stretched into a beam. Doing that with an SVG
transform chain looked obvious and wasn't:

  * a bolt is a DIAGONAL shape, so simply turning it a quarter turn gives a bar
    that visibly slopes downhill from left to right rather than a level meter;
  * a gradient inside a transformed <g> is defined in the group's own
    coordinates, so a left-to-right gradient written in final-image space comes
    out running along the bolt's short axis and reads as flat colour.

So the geometry is resolved here instead and written out as absolute
coordinates: no transform on the shape, no surprises about which space anything
is in, and the SVG stays legible.

The bolt's arcs are corner rounding of radius ~0.5 in a 36-unit box - about a
fifth of a pixel once this is 28px tall - so they're taken as corners.

    python3 tools/affinity_bar.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "game", "assets", "ui")

# Authored at 2x for a 70x14 slot, like the rest of the UI.
W, H = 140.0, 28.0
# Leaves the point at the right intact instead of clipping it at the viewBox
# edge, and keeps the thick end off the border.
PAD = 0.75

# lightning-solid, traced off the path in the source SVG. Arcs -> corners.
BOLT = [
    (30.80, 2.29), (30.35, 2.00), (16.42, 2.00), (16.00, 2.23),
    (5.29, 19.23), (5.70, 20.00), (13.37, 20.00), (6.60, 33.25),
    (7.06, 34.00), (10.06, 34.00), (10.43, 33.84), (28.00, 14.85),
    (27.63, 14.00), (20.89, 14.00), (30.72, 2.82),
]


def turn_sideways(pts):
    """Quarter turn, so the bolt's long axis becomes the bar's long axis.

    (x, y) -> (y, -x): the bolt's tip ends up on the right, which is the
    direction the bar fills in.
    """
    return [(y, -x) for x, y in pts]


def level(pts):
    """Take the slope out of it.

    A bolt leans, so after the turn the beam runs downhill. This measures the
    shape's own centre line - the midpoint between its top and bottom edge,
    sampled across its length - fits a slope to it, and shears that slope away.
    The result is a bar that sits level while every kink in the bolt survives.
    """
    xs = [p[0] for p in pts]
    lo, hi = min(xs), max(xs)
    samples = []
    for i in range(1, 40):
        x = lo + (hi - lo) * i / 40.0
        ys = _crossings(pts, x)
        if len(ys) >= 2:
            samples.append((x, (min(ys) + max(ys)) * 0.5))
    n = len(samples)
    mx = sum(s[0] for s in samples) / n
    my = sum(s[1] for s in samples) / n
    num = sum((s[0] - mx) * (s[1] - my) for s in samples)
    den = sum((s[0] - mx) ** 2 for s in samples)
    slope = num / den if den else 0.0
    return [(x, y - slope * x) for x, y in pts]


def _crossings(pts, x):
    """Where a vertical line at x cuts the outline."""
    out = []
    for i in range(len(pts)):
        x0, y0 = pts[i]
        x1, y1 = pts[(i + 1) % len(pts)]
        if (x0 <= x < x1) or (x1 <= x < x0):
            t = (x - x0) / (x1 - x0)
            out.append(y0 + t * (y1 - y0))
    return out


def fit(pts):
    """Scale into the viewBox, filling it on both axes."""
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    sx = (W - PAD * 2) / (max(xs) - min(xs))
    sy = (H - PAD * 2) / (max(ys) - min(ys))
    return [(PAD + (x - min(xs)) * sx, PAD + (y - min(ys)) * sy) for x, y in pts]


def path_d(pts):
    return "M" + " L".join("%.2f,%.2f" % p for p in pts) + " Z"


HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by tools/affinity_bar.py - edit that, not this.

  %s

  Shape: lightning-solid (SVG Repo, user-supplied), turned sideways, levelled
  and stretched into a %dx%d beam. Both bar files share this geometry exactly;
  the fill is revealed over the track, so any mismatch would fringe the edge.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d">
"""


def main():
    pts = fit(level(turn_sideways(BOLT)))
    d = path_d(pts)
    dims = (int(W), int(H), int(W), int(H), int(W), int(H))

    track = HEADER % (("The unfilled part of the affinity bar.",) + dims)
    track += '  <path d="%s" fill="#2f2f33" fill-opacity="0.85"/>\n</svg>\n' % d
    open(os.path.join(OUT, "affinity_bar_track.svg"), "w").write(track)

    # userSpaceOnUse across the real viewBox: the shape carries no transform
    # now, so gradient coordinates and shape coordinates are the same space.
    fill = HEADER % (("The filled part, revealed left to right by a clipping "
                      "parent - never scaled.",) + dims)
    fill += """  <defs>
    <linearGradient id="bolt" x1="0" y1="0" x2="%d" y2="0" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#f7791e"/>
      <stop offset="0.55" stop-color="#ffc51e"/>
      <stop offset="1" stop-color="#fff23c"/>
    </linearGradient>
  </defs>
  <path d="%s" fill="url(#bolt)"/>
</svg>
""" % (int(W), d)
    open(os.path.join(OUT, "affinity_bar_fill.svg"), "w").write(fill)

    ys = [p[1] for p in pts]
    print("  bar %gx%g, shape spans y %.1f-%.1f" % (W, H, min(ys), max(ys)))
    print("  wrote affinity_bar_track.svg + affinity_bar_fill.svg")


if __name__ == "__main__":
    main()
