#!/usr/bin/env python3
"""Write the build stamp Godot reads at runtime, from the git checkout.

WHY THIS EXISTS. The stamp used to be a hand-edited constant in save_game.gd,
and it drifted three times in a single day - because keeping it true meant a
commit and a pull request every time anything shipped, and nothing enforced it.
Worse, being committed forced it to be wrong on purpose: a constant cannot
contain the hash of the commit that contains it, so it named its own parent and
every reader had to remember the off-by-one.

Generating it fixes both. The file is not committed, so there is no PR and no
drift, and it can name the EXACT commit because it is written after that commit
exists rather than inside it.

    python3 tools/stamp.py        # before exporting a build

Run it from anywhere; paths are resolved against this file. A working tree with
uncommitted changes is stamped "<hash>+dirty", which is a fact worth having in
a save: it says the build did not come from a commit anybody else can check out.
"""
import pathlib
import subprocess
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "game" / "scripts" / "build_stamp.gd"


def git(*args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(ROOT), *args],
        capture_output=True, text=True, check=True,
    ).stdout.strip()


def main() -> int:
    try:
        short = git("rev-parse", "--short", "HEAD")
        dirty = bool(git("status", "--porcelain"))
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"stamp: no git here ({exc}); leaving the stamp alone", file=sys.stderr)
        return 1

    stamp = f"{short}+dirty" if dirty else short
    built = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    OUT.write_text(
        "# GENERATED BY tools/stamp.py - DO NOT EDIT, DO NOT COMMIT.\n"
        "#\n"
        "# Written just before an export so a save can say which build wrote it.\n"
        "# Absent in a fresh clone and in the editor, which is why SaveGame falls\n"
        "# back to \"dev\" rather than preloading this.\n"
        "extends RefCounted\n"
        "\n"
        f'const HASH := "{stamp}"\n'
        f'const BUILT_AT := "{built}"\n',
        encoding="utf-8",
    )
    print(f"stamped {stamp} ({built}) -> {OUT.relative_to(ROOT)}")
    if dirty:
        print("  note: working tree is dirty, so this build is not reproducible "
              "from a commit", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
